services:
   symfony:
      build: docker/symfony
      ports:
        - 8000:8000
      volumes: 
        - ./data:/data
      links:
        - "mysql:database"
   mysql:
      image: mariadb
      volumes:
        - ./mariadb/data:/var/lib/mysql
      environment:
        - MARIADB_ROOT_PASSWORD=root
   phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
        - 8080:80
      links:
        - "mysql:db"
